version: "3"
services:
    # Define the backend (API) service
    orchestrator:
        container_name: orchestrator
        build:
            context: ./orchestrator
        # Expose port 8080 to the Docker host for use with NGINX
        ports:
            - "8080:8080"
        # Define environment variables
        env_file:
            - .env
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
